### ISSUE TITLE
langchain-core和langchain-community版本问题

### ISSUE THREAD

**Issue by jousonren** [bytesc/data-copilot#1]
pip install -r requirements.txt安装时候会有如下报错：
ERROR: Cannot install -r requirements.txt (line 2) and langchain-core==0.2.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain-core==0.2.2
    langchain-community 0.0.29 depends on langchain-core<0.2.0 and >=0.1.33

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by bytesc** [comment]
@jousonren  你好，感想发现问题。

这个问题是由于我 `requirements.txt ` 依赖列表编写问题

问题是否已经通过以下方式解决？

```txt
To fix this you could try to:

loosen the range of package versions you've specified
remove package versions to allow pip attempt to solve the dependency conflict
```

我更新了依赖列表 以解决问题
https://github.com/bytesc/data-copilot/commit/379af3090cd1ba3ddb88ebacfe63a4e903e381d2
